### PR TITLE
gitignore, SASS Sourcemaps, grunt watch, grunt sass compiling

### PR DESCRIPTION
**Pull request by jclaw**
I modified .gitignore to leave out node modules, bower components, and compiled css in "stylesheets". Run bower install to download the bower components, npm install to download node modules, and run grunt to compile the css.

I added the option to the grunt sass process to include sourcemaps, which means that you can inspect the TEDx page that you're working on and the Chrome devtools will tell you the actual sass file the rules are defined in rather than showing the compiled app.css.

I added a grunt watch task that will recompile the sass when it notices a change. It is separate from the default grunt task, so run "grunt" in one terminal window/tab and run "grunt watch" in another.

I split the sass compilation into two separate tasks, one for foundation and one for our custom sass. That way, when watch notices a change, it only has to recompile our custom sass, which is much faster.

### CODE REVIEW

**Comment by jclaw** [comment]
@rachaelrobinson let me know if I should merge

**Comment by jclaw** [comment]
To clarify, I split the foundation and custom sass compilation into two separate processes, which means they also get compiled into separate files. As a result, I included foundation.css in our base.html, listed before app.css.

**Comment by rachaelrobinson** [comment]
This looks great. Could you add these additional things (ie running a separate grunt watch and the installs) to the read me?

**Comment by jclaw** [comment]
Updated the readme! I made a new "Getting Started" section and took out the grunt info that was in the "How To Edit Pages" section

**Pull request merged**
